#!/bin/bash

LOGGING=1 # Either 1 or 0

RUNDIRS=$(echo run[0-9][0-9][0-9])
RUNDIR=${RUNDIRS##*\ }
LOG=$RUNDIR/scripts/log


RADICAL_PY=/home/yadunand/swift-k/cogkit/modules/provider-localscheduler/libexec/radical-pilot-provider/thrift_tests/client.py

[[ "$LOGGING" == "1" ]] && mkdir -p $(dirname $LOG)
log()
{
    [[ "$LOGGING" == "1" ]] && echo $* >> $LOG
}

JOBID=$1

if [[ "$1" != "" ]]
then
    log "Stat'ing for $1 PWD: $PWD"
    python $RADICAL_PY --logfile $LOG --status $1 | tee -a $LOG
fi
